# Generated by Django 3.0.1 on 2020-02-10 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(default=' ', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(default='Manager', max_length=15, unique=True),
        ),
    ]
