# Generated by Django 3.0.1 on 2020-02-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200210_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(default='01111', max_length=30),
        ),
    ]
