# Generated by Django 3.0.1 on 2020-02-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200210_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.CharField(default='manager', max_length=30),
        ),
    ]
