# Generated by Django 3.0.1 on 2020-02-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
