# Generated by Django 3.0.1 on 2020-02-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_account_is_check'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='role',
        ),
        migrations.AddField(
            model_name='account',
            name='is_role',
            field=models.BooleanField(default=True),
        ),
    ]
