# Generated by Django 3.0.1 on 2020-02-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20200216_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_ceo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_manager',
            field=models.BooleanField(default=True),
        ),
    ]
