# Generated by Django 3.0.1 on 2019-12-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.IntegerField(null=True, unique=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit_type', models.CharField(max_length=10)),
                ('unit_price', models.IntegerField()),
                ('status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='date updated')),
            ],
        ),
    ]
