# Generated by Django 3.0.1 on 2019-12-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
