# Generated by Django 3.0.1 on 2020-01-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20191230_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default='raw', max_length=250),
        ),
    ]
