# Generated by Django 3.0.1 on 2020-02-10 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_profile',
            options={'verbose_name': 'user_profile'},
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='phn',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='role',
        ),
    ]
