# Generated by Django 3.0.1 on 2020-02-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20200210_1214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Profile',
        ),
    ]
